spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/videostreaming
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: POSTGRESQL

minio:
  url: http://localhost:9000
  username: admin
  password: adminpass